db.execSQL("insert into " + TABLE_QU + " values(null, 'What is the 1st Planet from the Sun?', 'Mercury', 'Neptune', 'Earth', 'Jupiter')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What is the 2nd Planet from the Sun', 'Venus', 'Mercury', 'Uranus', 'Neptune')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What is the 3rd Planet from the Sun?', 'Earth', 'Saturn', 'Venus', 'Neptune')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What is the 4th Planet from the Sun?', 'Mars', 'Venus', 'Uranus', 'Saturn')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What is the 5th Planet from the Sun', 'Jupiter', 'Mars', 'Uranus', 'Saturn')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What is the 6th Planet from the Sun', 'Saturn', 'Neptune', 'Earth', 'Jupiter')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What is the 7th Planet from the Sun?', 'Uranus', 'Saturn', 'Venus', 'Mars')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What is the 8th Planet from the Sun?', 'Neptune', 'Mercury', 'Jupiter', 'Earth')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'How many known planets are there in the Solar System?', '8', '5', '7', '11')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What is the largest planet in the Solar System?', 'Jupiter', 'Earth', 'Saturn', 'Uranus')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What is the Sun?', 'Star', 'Planet', 'Moon', 'Black hole')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'How long does it take the Earth to revolve around the sun?', '365 Days', '180 Days', '730 Days', '1 Day')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'All of the following are inner planets except?', 'Neptune', 'Earth', 'Mars', 'Venus')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What sepeartes the inner and outer planets?', 'The Astroid Belt', 'Mars', 'Jupiter', 'Halley''s Commet')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What is at the center of the Solar System?', 'The Sun', 'Earth', 'Jupiter', 'Pluto')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'Our solar system is located in which galaxy?', 'The Milky Way', 'Andromeda ', 'M32', 'Triangulum')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What is the smallest planet in the Solar System?', 'Mercury', 'Earth', 'Mars', 'Neptune')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What type of force is holding us to the Earth?', 'gravity', 'tension', 'friction', 'magnetic')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'What is the hottest planet in our solar system?', 'Venus', 'Mercury', 'Mars', 'Saturn')");
db.execSQL("insert into " + TABLE_QU + " values(null, 'Which one of these used to be a planet?', 'Pluto', 'Ceres', 'Eris', 'Sedna')");
